# Generated by Django 4.1.3 on 2022-12-07 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0022_remove_myusercreate_father_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(blank=True, max_length=70, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=70, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('incharge', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='student_profile')),
                ('DOB', models.DateField(blank=True, default=None, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('teacher_age', models.IntegerField(blank=True, default=None, null=True)),
                ('experience', models.CharField(max_length=20)),
                ('subject_teaches', models.CharField(max_length=50)),
                ('date_join', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.myusercreate')),
            ],
        ),
    ]
