# Generated by Django 4.1.3 on 2022-12-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_profile',
            name='date_join',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_profile',
            name='experience',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_profile',
            name='subject_teaches',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
