# Generated by Django 4.1.3 on 2022-11-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_date', models.DateField()),
                ('notify_time', models.TimeField()),
                ('notification', models.CharField(max_length=200)),
                ('notify_by', models.CharField(max_length=70)),
            ],
        ),
    ]
