# Generated by Django 4.1.3 on 2022-11-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('department', models.CharField(max_length=100)),
                ('incharge', models.CharField(max_length=100)),
                ('event_image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
            ],
        ),
    ]
