# Generated by Django 4.1.3 on 2022-11-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_event_incharge_event_event_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='event',
            name='phone',
            field=models.CharField(default=None, max_length=12),
        ),
    ]
