# Generated by Django 4.1.3 on 2022-11-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_event_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('fees', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('subjects', models.CharField(max_length=200)),
                ('department_head', models.CharField(max_length=70)),
                ('semester', models.IntegerField()),
                ('duration', models.CharField(max_length=30)),
                ('eligiblity', models.CharField(max_length=100)),
            ],
        ),
    ]
