# Generated by Django 4.1.3 on 2022-11-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='seats',
            field=models.IntegerField(default=100),
        ),
    ]
