# Generated by Django 4.1.3 on 2022-11-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_course_bgein_course_ends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='bgein',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='ends',
            field=models.DateField(default=None, null=True),
        ),
    ]
