# Generated by Django 4.1.3 on 2022-11-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_course_bgein_alter_course_ends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='bgein',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='ends',
            field=models.DateField(blank=True, null=True),
        ),
    ]
