# Generated by Django 4.1.3 on 2022-11-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_course_bgein_alter_course_ends'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='pdfurl',
            field=models.URLField(default=None, max_length=300),
        ),
    ]
