# Generated by Django 4.1.3 on 2022-11-30 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='image',
            new_name='event_image',
        ),
    ]
