# Generated by Django 4.1.3 on 2022-12-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_feedback_feedtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusercreate',
            name='father_name',
            field=models.CharField(default=None, max_length=70),
        ),
        migrations.AddField(
            model_name='myusercreate',
            name='incharge',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='myusercreate',
            name='mother_name',
            field=models.CharField(default=None, max_length=70),
        ),
        migrations.AddField(
            model_name='myusercreate',
            name='phone',
            field=models.CharField(default=None, max_length=12),
        ),
        migrations.AddField(
            model_name='myusercreate',
            name='semester',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='myusercreate',
            name='stu_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
