# Generated by Django 4.1.3 on 2022-12-03 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_myusercreate_father_name_myusercreate_incharge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myusercreate',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='myusercreate',
            name='incharge',
        ),
        migrations.RemoveField(
            model_name='myusercreate',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='myusercreate',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='myusercreate',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='myusercreate',
            name='stu_class',
        ),
    ]
