# Generated by Django 4.1.3 on 2022-12-08 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0022_remove_myusercreate_father_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutpdf', models.CharField(max_length=200)),
                ('mainpdf', models.FileField(null=True, upload_to='stundent_pdf/')),
                ('pdf_by', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(blank=True, max_length=70, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=70, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('stu_class', models.CharField(blank=True, max_length=50, null=True)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='student_profile')),
                ('DOB', models.DateField(blank=True, default=None, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('stu_age', models.IntegerField(blank=True, default=None, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.myusercreate')),
            ],
        ),
        migrations.CreateModel(
            name='Student_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('message_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('status', models.BooleanField()),
                ('last_date', models.DateField(default=None)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
